# Generated by Django 3.0.3 on 2020-03-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.SmallIntegerField(choices=[(1, 'A través de depósito bancario'), (3, 'A través de tarjeta de crédito'), (5, 'A través de tarjeta de débito')], default=3)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Evento pagado.'), (3, 'Pendiente de pago'), (5, 'Pago cancelado')], default=3)),
                ('total', models.FloatField()),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Eventos')),
            ],
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Recibo pagado'), (3, 'Recibo con devolución'), (5, 'Recibo cancelado, dinero devuelto')], default=1)),
                ('idPago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pagos.Pagos')),
            ],
        ),
    ]
