# Generated by Django 3.0.3 on 2020-05-14 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_auto_20200514_0402'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='idEvento',
            new_name='evento',
        ),
        migrations.RemoveField(
            model_name='recibos',
            name='idPago',
        ),
        migrations.AddField(
            model_name='pagos',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagos',
            name='recibo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Pagos.Recibos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
