# Generated by Django 3.0.3 on 2020-04-23 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_pagos_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='idEvento',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='idUsuario',
        ),
        migrations.AlterField(
            model_name='recibos',
            name='idPago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Pagos.Pagos'),
        ),
    ]
