# Generated by Django 3.0.3 on 2020-04-23 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0004_auto_20200423_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibos',
            name='idPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='Pagos.Pagos'),
        ),
    ]
