# Generated by Django 3.0.3 on 2020-04-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0005_auto_20200423_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibos',
            name='idPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='Pagos.Pagos'),
        ),
    ]
