# Generated by Django 3.0.3 on 2020-04-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con ese correo.'}, max_length=254, unique=True, verbose_name='email_address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Verdadero si el usuario es un administrador del sitio.', verbose_name='administrador'),
        ),
    ]
