# Generated by Django 3.0.3 on 2020-04-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20200414_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre de usuario.'}, max_length=50, unique=True, verbose_name='username'),
        ),
    ]
