# Generated by Django 3.0.3 on 2020-04-22 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0013_auto_20200422_2110'),
        ('Usuarios', '0003_auto_20200414_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Eventos.Comentarios'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='valoraciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='Eventos.Valoraciones'),
        ),
    ]
