# Generated by Django 3.0.3 on 2020-03-10 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoraciones',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localidad',
            name='idAsiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Asientos'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='idTipoLocal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.TipoLocal'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='idComentarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Eventos.Comentarios'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='idLocalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Eventos.Localidad'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='idValoracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Eventos.Valoraciones'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
