# Generated by Django 3.0.3 on 2020-03-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_auto_20200310_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='idComentarios',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='idLocalidad',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='idValoracion',
        ),
    ]
