# Generated by Django 3.0.3 on 2020-04-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_auto_20200326_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='asientos_totales',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='idTipoLocal',
        ),
        migrations.AddField(
            model_name='localidad',
            name='costo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localidad',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Asiento General'), (3, 'Asiento Oro'), (5, 'Asiento Platinum')], default=1),
        ),
        migrations.DeleteModel(
            name='TipoLocal',
        ),
    ]
