# Generated by Django 3.0.3 on 2020-05-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0004_auto_20200514_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='usuario',
            new_name='owner',
        ),
    ]
