# Generated by Django 3.0.3 on 2020-05-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0005_auto_20200515_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='owner',
            new_name='usuario',
        ),
    ]
