# Generated by Django 3.0.3 on 2020-04-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0005_auto_20200422_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientos',
            name='idLocalidad',
        ),
        migrations.AddField(
            model_name='localidad',
            name='idAsiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Asientos'),
            preserve_default=False,
        ),
    ]
