# Generated by Django 3.0.3 on 2020-04-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0006_auto_20200422_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='idComentarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Eventos.Comentarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='idLocalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Eventos.Localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='idValoracion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Eventos.Valoraciones'),
            preserve_default=False,
        ),
    ]
