# Generated by Django 3.0.3 on 2020-04-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0007_auto_20200422_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='idComentarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Comentarios'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='idLocalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Localidad'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='idValoracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Valoraciones'),
        ),
    ]
