# Generated by Django 3.0.3 on 2020-04-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0010_auto_20200422_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='idAsiento',
        ),
        migrations.AddField(
            model_name='asientos',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Localidad'),
        ),
    ]
