# Generated by Django 3.0.3 on 2020-04-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0011_auto_20200422_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientos',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='Eventos.Localidad'),
        ),
    ]
