# Generated by Django 3.0.3 on 2020-04-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0012_auto_20200422_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='valoraciones',
            name='idUsuario',
        ),
    ]
