# Generated by Django 3.0.3 on 2020-04-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0013_auto_20200422_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='idComentarios',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='idLocalidad',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='idValoracion',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventosComent', to='Eventos.Eventos'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventosLocal', to='Eventos.Eventos'),
        ),
        migrations.AddField(
            model_name='valoraciones',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventosVal', to='Eventos.Eventos'),
        ),
    ]
