# Generated by Django 3.0.3 on 2020-03-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Asiento libre'), (2, 'Asiento reservado')], default=1)),
                ('idLocalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Eventos')),
            ],
        ),
    ]
